ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - maplibre-gl
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - '@sentry/cli'
  - protobufjs
  - sharp
  - supabase
