name: Feature Request
description: Suggest a new feature.
title: "[Question]: "
labels: ["Status: Triage"]
type: ❔ Discussion
body:
  - type: markdown
    attributes:
      value: |
        ### Please read the following:
        Thanks for taking the time to fill out this question form!

        Before submitting a question form, please make sure you have searched through the existing issues to make sure your question is not a duplicate.

        If your question is still valid, please change the title of this issue to reflect your question and fill out the fields below.
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: Be as detailed as possible!
      placeholder: I wonder ...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmations
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mtdvlpr-org/bible-time/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I confirm that I have searched through the existing issues to make sure my question is not a duplicate.
          required: true
